const getExercises = () => {
  const pathToImages = "../assets/images/";

  return [
    {
      id: 1,
      image: `${pathToImages}restau.webp`,
      mobileImage: null,
      tags: ["html", "css", "js"],
      link: null,
      class: "restau",
      animation: "restauAnimation",
      text: null,
    },
    {
      id: 2,
      image: `${pathToImages}hello.webp`,
      mobileImage: null,
      tags: ["html", "css"],
      link: null,
      class: "hello",
      animation: "helloAnimation",
      text: null,
    },
    {
      id: 3,
      image: `${pathToImages}archi.webp`,
      mobileImage: null,
      tags: ["html", "css"],
      link: null,
      class: "archi",
      animation: "archiAnimation",
      text: null,
    },
    {
      id: 4,
      image: `${pathToImages}fake.webp`,
      mobileImage: `${pathToImages}fake-mobile.webp`,
      tags: ["html", "scss", "js", "php", "sql"],
      link: null,
      class: "fake",
      animation: "fakeAnimation",
      text: null,
    },
    {
      id: 5,
      image: `${pathToImages}blog.webp`,
      mobileImage: null,
      tags: ["twig", "bootstrap", "symfony"],
      link: null,
      class: "blog",
      animation: "blogAnimation",
      text: null,
    },
    {
      id: 6,
      image: `${pathToImages}shop.webp`,
      mobileImage: null,
      tags: ["twig", "bootstrap", "symfony"],
      link: null,
      class: "shop",
      animation: "shopAnimation",
      text: null,
    },
    {
      id: 7,
      image: `${pathToImages}aw.webp`,
      mobileImage: null,
      tags: ["python"],
      link: null,
      class: "aw",
      animation: "awAnimation",
      text: null,
    },
    {
      id: 8,
      image: null,
      mobileImage: null,
      tags: ["python"],
      link: "https://github.com/requenaGuillaume93400/pdf-merger",
      class: "gitLinks",
      text: "Pdf merger/splitter",
    },
    {
      id: 9,
      image: null,
      mobileImage: null,
      tags: ["python"],
      link: "https://github.com/requenaGuillaume93400/ytb",
      class: "gitLinks",
      text: "YouTube video/audio (single and playlist) downloader",
    },
    {
      id: 10,
      image: `${pathToImages}artwork.webp`,
      mobileImage: null,
      tags: ["react", "scss"],
      link: null,
      class: "artwork",
      animation: "artworkAnimation",
      text: null,
    },
    {
      id: 11,
      image: null,
      mobileImage: null,
      tags: ["html", "php", "bootstrap"],
      link: "https://github.com/requenaGuillaume93400/blogOC",
      class: "gitLinks",
      text: "Blog php natif (Github)",
    },
    {
      id: 12,
      image: null,
      mobileImage: null,
      tags: ["wordpress"],
      link: "https://guillaumereq.sites.3wa.io/cv/chalets-et-caviar-immobilier/",
      class: "gitLinks",
      text: "Wordpress - Chalets & Caviar (Site)",
    },
    {
      id: 13,
      image: null,
      mobileImage: null,
      tags: ["symfony", "twig", "bootstrap"],
      link: "https://github.com/requenaGuillaume93400/snowtricks",
      class: "gitLinks",
      text: "Blog symfony - Snowtricks (Github)",
    },
    {
      id: 14,
      image: null,
      mobileImage: null,
      tags: ["symfony", "twig", "bootstrap"],
      link: "https://github.com/requenaGuillaume93400/BileMo",
      class: "gitLinks",
      text: "Api Restfull - BileMo (Github)",
    },
    {
      id: 15,
      image: null,
      mobileImage: null,
      tags: ["symfony", "twig", "bootstrap"],
      link: "https://github.com/requenaGuillaume93400/todolist",
      class: "gitLinks",
      text: "Upgrade php/symfony versions and add tests - Todolist (Github)",
    },
    {
      id: 16,
      image: `${pathToImages}portfolio.webp`,
      mobileImage: null,
      tags: ["vue", "html", "css"],
      link: null,
      class: "portfolio",
      animation: "",
      text: null,
    },
  ];
};

export default getExercises;
